task_one_v2/Models/Testimonial.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace task_one_v2.Models;

public partial class Testimonial
{
    public decimal TestimonialId { get; set; }
    public decimal? UserId { get; set; }
    [DisplayName("Testimonial Text Area")]
    [MaxLength(255),MinLength(40)]
    public string TestimonialText { get; set; } = null!;
    public DateTime? DateTime { get; set; }
    [DisplayName("Approval Status")]
    public decimal? ApprovalStatusId { get; set; }
    public string? Userimg { get; set; }
    public virtual TestimonialApprovalStatus? ApprovalStatus { get; set; } /* = null!;*/
    public virtual UserInfo? User { get; set; } /*= null!;*/
}

task_one_v2/Controllers/TestimonialsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using task_one_v2.App_Core.ConstString;
using task_one_v2.App_Core.StateMangement;
using task_one_v2.Models;

namespace task_one_v2.Controllers
{
    public class TestimonialsController : Controller
    {
        private readonly ModelContext _context;
        private readonly IAuthManager _authManager;

        public TestimonialsController(ModelContext context, IAuthManager authManager)
        {
            _context = context;
            _authManager = authManager;
        }



        public IActionResult CreateTestimonial()
        {
            ViewData["ApprovalStatusId"] = new SelectList(_context.TestimonialApprovalStatuses, "ApprovalStatusId", "StatusName");
            ViewData["UserId"] = new SelectList(_context.UserInfos, "Userid", "Userid");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTestimonial([Bind("TestimonialId,UserId,TestimonialText,DateTime,StatusName,Userimg")] Testimonial testimonial)
        {
            var currentUserData = _authManager.GetCurrentUserData();
            if (currentUserData == null) return NotFound();
            if (String.IsNullOrEmpty(testimonial.TestimonialText)) {
                ModelState.AddModelError("","");
            }
            testimonial.DateTime = DateTime.Now;
            testimonial.ApprovalStatusId = ConstantApp.pendingTestimonial;
            testimonial.UserId = currentUserData?.Userid ?? 0;
            testimonial.Userimg = currentUserData?.Image?? "~/Globalimg/chef_demo.jpg";
            if (ModelState.IsValid)
            {
                _context.Add(testimonial);
                await _context.SaveChangesAsync();
                return RedirectToAction("AllTestimonial", "Admin");
            }
            ViewData["ApprovalStatusId"] = new SelectList(_context.TestimonialApprovalStatuses, "ApprovalStatusId", "StatusName", testimonial.ApprovalStatusId);
            ViewData["UserId"] = new SelectList(_context.UserInfos, "Userid", "Userid", testimonial.UserId);
            return View(testimonial);
        }
        public async Task<IActionResult> Delete(decimal? id)
        {
            if (id == null || _context.Testimonials == null)
            {
                return NotFound();
            }
            var testimonial = await _context.Testimonials
                .Include(t => t.ApprovalStatus)
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.TestimonialId == id);
            if (testimonial == null)
            {
                return NotFound();
            }
            return View(testimonial);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(decimal id)
        {
            if (_context.Testimonials == null)
            {
                return Problem("Entity set 'ModelContext.Testimonials'  is null.");
            }
            var testimonial = await _context.Testimonials.FindAsync(id);
            if (testimonial != null)
            {
                _context.Testimonials.Remove(testimonial);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("AllTestimonial", "Admin");
        }

        private bool TestimonialExists(decimal id)
        {
          return (_context.Testimonials?.Any(e => e.TestimonialId == id)).GetValueOrDefault();
        }
    }
}

task_one_v2/Views/Testimonials/CreateTestimonial.cshtml
@model Testimonial
@using task_one_v2.App_Core.ConstString
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer localizer

@{
    Layout = ConstantApp.homeLayout;
}
<div class="container m-5 p-5">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="CreateTestimonial" asp-controller="Testimonials">
                <div class="form-group">
                    <label asp-for="TestimonialText" class="control-label"></label>
                    <textarea asp-for="TestimonialText" class="form-control" rows="4"></textarea>
                    <span asp-validation-for="TestimonialText" class="text-danger"></span>
                </div>
                @* hidden data *@
                <input type="hidden" asp-for="UserId" class="form-control" asp-items="ViewBag.UserId" />
                <input type="hidden" asp-for="TestimonialText" class="form-control" />
                <input type="hidden" asp-for="Userimg" class="form-control" />
                <input type="hidden" asp-for="ApprovalStatusId" class="form-control" asp-items="ViewBag.ApprovalStatusId" />
                <input type="hidden" asp-for="DateTime" class="form-control" />
                @* end hidden data *@
                <div class="form-group">
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

task_one_v2/Views/Testimonials/Delete.cshtml
@model Testimonial

@using task_one_v2.App_Core.ConstString
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer localizer
@{
    Layout = ConstantApp.adminLayout;
}


 
<h3>@localizer["Are you sure you want to delete this?"]</h3>
<div>
    <h4>@localizer["testimonials"]</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @localizer["testimonials"]
        </dt>
        <dd class="col-sm-10">
            @Model.TestimonialText
        </dd>
        <dt class="col-sm-2">
            @localizer["CreationDate"]
        </dt>
        <dd class="col-sm-10">
            @Model.DateTime.?ToString("yyyy-MM-dd")
        </dd>
        <dt class="col-sm-2">
            @localizer["Personal Image"]
        </dt>
        <dd class="col-sm-10">
            <img style="max-width:150px; max-height:150px" src="@Url.Content(ConstantApp.wwwImgPath + Model.Userimg)" />
        </dd>
        <dt class="col-sm-2">
            @localizer["Full Name"]
        </dt>
        <dd class="col-sm-10">
            @Model.User.FirstName @Model.User.LastName
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TestimonialId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

task_one_v2/Views/Testimonials/Index.cshtml
@* @model IEnumerable<Testimonial>

@using task_one_v2.App_Core.ConstString
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer localizer
@{
    Layout = ConstantApp.adminLayout;
}

<link href="https://cdn.datatables.net/1.11.1/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/buttons/2.0.0/css/buttons.dataTables.min.css" rel="stylesheet" />

<div class="grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <table class="table" id="Testimonial">
                <thead>
                    <tr>
                        <th>
                            @localizer["Full Name"]
                        </th>
                        <th>
                            @localizer["testimonials"]
                        </th>
                        <th>
                            @localizer["Personal Image"]
                        </th>
                        <th>
                            @localizer["Approval Status"]
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <textarea style=" border: none; background-color: transparent;" rows="4" cols="15" disabled>
                                    @item?.User?.FirstName @item?.User?.LastName
                                 </textarea>
                            </td>
                            <td>
                                <textarea style=" border: none; background-color: transparent;" rows="4" cols="40" disabled>@item?.TestimonialText</textarea>
                            </td>
                            <td style="max-width: 50px;">
                                <a href="@Url.Content(ConstantApp.wwwImgPath + item?.Userimg)" target="_blank">
                                    <img src="@Url.Content(ConstantApp.wwwImgPath + item?.Userimg)" alt="User Image" width="100%" height="200">
                                </a>
                            </td>

                            <td>
                                <label class="badge
                                   @{
                                   if(item?.ApprovalStatus?.ApprovalStatusId == ConstantApp.approvedTestimonial)
                                   {
                                                  <text>badge-success</text>
                                       }
                                       else if(item?.ApprovalStatus?.ApprovalStatusId == ConstantApp.pendingTestimonial)
                                       {
                                                 <text>badge-warning</text>
                                       }
                                        else
                                       {
                                                 <text>badge-danger</text>
                                       }
                                      }">
                                    @item?.ApprovalStatus?.StatusName.ToLower()</label>
                            </td>
                            <td>
                                <a asp-action="Delete" asp-route-id="@item?.TestimonialId">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.1/js/jquery.dataTables.min.js" defer></script>
<script src="https://cdn.datatables.net/buttons/2.0.0/js/dataTables.buttons.min.js" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.0/js/buttons.html5.min.js" defer></script>

<script>
    $(document).ready(function () {
        $('#Testimonial').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5'
            ]
        });
    });
</script>
 *@