task_one_v2/Models/ContactU.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace task_one_v2.Models;

public partial class ContactU
{
    public decimal Contactid { get; set; }

    [Display(Name = "Full Name")]
    [Required(ErrorMessage = "Name is required")]
    [StringLength(20, ErrorMessage = "Name must be between 1 and 20 characters", MinimumLength = 1)]
    public string Name { get; set; } = null!;

    [Display(Name = "Email")]
    [Required(ErrorMessage = "Email is required")]
    [EmailAddress(ErrorMessage = "Invalid email address")]
    public string Email { get; set; } = null!;

    [Display(Name = "Subject")]
    [Required(ErrorMessage = "Subject is required")]
    [StringLength(20, ErrorMessage = "Subject must be between 1 and 20 characters", MinimumLength = 1)]
    public string Subject { get; set; } = null!;

    [Display(Name = "Message")]
    [Required(ErrorMessage = "Message is required")]
    [StringLength(500, ErrorMessage = "Message must be between 1 and 500 characters", MinimumLength = 1)]
    public string Message { get; set; } = null!;
}

task_one_v2/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using task_one_v2.App_Core.StateMangement;
using task_one_v2.Models;

namespace task_one_v2.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly ModelContext _context;
        private readonly IUserManager _userManger;

        public ContactUsController(ModelContext context, IUserManager userManger)
        {
            _context = context;
            _userManger = userManger;
        }



        // GET: ContactUs/Details/5
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null || _context.ContactUs == null)
            {
                return NotFound();
            }

            var contactU = await _context.ContactUs
                .FirstOrDefaultAsync(m => m.Contactid == id);
            if (contactU == null)
            {
                return NotFound();
            }

            return View(contactU);
        }





        public async Task<IActionResult> Delete(decimal? id)
        {
            if (id == null || _context.ContactUs == null)
            {
                return NotFound();
            }

            var contactU = await _context.ContactUs
                .FirstOrDefaultAsync(m => m.Contactid == id);
            if (contactU == null)
            {
                return NotFound();
            }

            return View(contactU);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(decimal id)
        {
            if (_context.ContactUs == null)
            {
                return Problem("Entity set 'ModelContext.ContactUs'  is null.");
            }
            var contactU = await _context.ContactUs.FindAsync(id);
            if (contactU != null)
            {
                _context.ContactUs.Remove(contactU);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("AllContactUs", "Admin");
        }

        private bool ContactUExists(decimal id)
        {
          return (_context.ContactUs?.Any(e => e.Contactid == id)).GetValueOrDefault();
        }



        public IActionResult CreateContact() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateContact([Bind("Contactid,Name,Email,Subject,Message")] ContactU contactU)
        {
            if (ModelState.IsValid)
            {
                bool isSuccess = await _userManger.SendContactUs(contactU);
                if (isSuccess) return RedirectToAction("Home","Home");
                else return NotFound();
            }
            return View(contactU);
        }
    }
}

task_one_v2/Views/ContactUs/CreateContact.cshtml
@model ContactU
@using task_one_v2.App_Core.ConstString
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer localizer


@{
    Layout = ConstantApp.homeLayout;
}
<div class="py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">@localizer["Contact"]</h1>
    </div>
</div>

<div class="py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h5 class="section-title ff-secondary text-center text-primary fw-normal">@localizer["Contact"]</h5>
            <h1 class="mb-5">@localizer["Contact For Any Query"]</h1>
        </div>
        <div class="row g-4">

            <div class="col-md-6 wow fadeIn" data-wow-delay="0.1s">
                <iframe class="position-relative rounded w-100 h-100"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                        frameborder="0" style="min-height: 350px; border:0;" allowfullscreen="" aria-hidden="false"
                        tabindex="0"></iframe>
            </div>
            <div class="col-md-6">
                <div class="wow fadeInUp" data-wow-delay="0.2s">
                    <form asp-action="CreateContact" asp-controller="ContactUs">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row g-3">
                            <div class="col-md-6">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label asp-for="Email" class="control-label"></label>
                                <input asp-for="Email" class="form-control" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                            <div class="col-12">
                                <label asp-for="Subject" class="control-label"></label>
                                <input asp-for="Subject" class="form-control" />
                                <span asp-validation-for="Subject" class="text-danger"></span>
                            </div>
                            <div class="col-12">
                                <label asp-for="Message" class="control-label"></label>
                                <input asp-for="Message" class="form-control" />
                                <span asp-validation-for="Message" class="text-danger"></span>
                            </div>
                            <div class="col-12">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

task_one_v2/Views/ContactUs/Delete.cshtml
@model ContactU

@using task_one_v2.App_Core.ConstString
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer localizer
@{
    Layout = ConstantApp.adminLayout;
}


<h3>@localizer["Are you sure you want to delete this?"]</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Contactid" />
        <button type="submit" class="btn btn-danger" title="Delete Contact">@localizer["delete"]</button>
    </form>
</div>

task_one_v2/Views/ContactUs/Details.cshtml
@model ContactU

@using task_one_v2.App_Core.ConstString
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer localizer
@{
    Layout = ConstantApp.adminLayout;
}


<h3>@localizer["Details"]</h3>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
    </dl>
</div>

task_one_v2/Views/ContactUs/Index.cshtml
@model IEnumerable<ContactU>

@using task_one_v2.App_Core.ConstString
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer localizer
@{
    Layout = ConstantApp.adminLayout;
}


<link href="https://cdn.datatables.net/1.11.1/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/buttons/2.0.0/css/buttons.dataTables.min.css" rel="stylesheet" />





<div class="grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <table class="table" id="contactUs">

                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Subject)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Message)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <textarea style=" border: none; background-color: transparent;" rows="1" cols="15" disabled>@item.Name</textarea>
                            </td>
                            <td>
                                <textarea style=" border: none; background-color: transparent;" rows="1" cols="15" disabled>@item.Email</textarea>


                            </td>
                            <td>
                                <textarea style=" border: none; background-color: transparent;" rows="4" cols="15" disabled>@item.Subject</textarea>
                            </td>

                            <td>
                                <textarea style=" border: none; background-color: transparent;" rows="4" cols="40" disabled>@item.Message</textarea>
                            </td>


                            <td>
                                <a asp-action="Details" asp-route-id="@item.Contactid">@localizer["Details"]</a> |
                                <a asp-action="Delete" asp-route-id="@item.Contactid">@localizer["delete"]</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>









<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.1/js/jquery.dataTables.min.js" defer></script>

<script src="https://cdn.datatables.net/buttons/2.0.0/js/dataTables.buttons.min.js" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.0/js/buttons.html5.min.js" defer></script>

<script>
    $(document).ready(function () {
        $('#contactUs').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5'
            ]
        });
    });
</script>